#!/usr/bin/env python3.9
# -*- coding: utf-8 -*-

from os.path import expanduser
import argparse

class MessagingAppsManager:
    
    def __init__(self):
        pass
    
    def createArgumentParser():
        # https://docs.python.org/3/howto/argparse.html
        # import argparse
        # parser = argparse.ArgumentParser()
        # parser.add_argument("square", help="display a square of a given number",
        #                     type=int)
        # args = parser.parse_args()


        # Also
        # parser.parse_args() print an error if this is mistake
        
        # more consize https://stackoverflow.com/a/30493366

        pass

    def printVersion():
        pass

    def sendMessageToPeopleFromInterestName(stringMessage, interestName):
        pass

    def sendMessageToPersonName(stringMessage, personNameString):
        pass

    def printProgramUsage():
        #import argparse
        # parser = argparse.ArgumentParser()
        # parser.add_argument("echo")
        # args = parser.parse_args()
        # print(args.echo)
        pass

    def parseArgumentsAndExecuteCommand():
        pass

    def getUsersInfoFromInterestList(interestName):
        # airtable.search('interest', interestName)
        pass

    def areArgumentsCorrectlyFormatted(argument):
        pass

    def sendMessageFromFileToPeopleToPeopleList(fileName, peopleList):
        pass

    def doesFileExist(filePath)
        pass

    def printFileNameDoesNotExist(filePath):
        pass

    def printConfigurationFileIsAbsent():
        pass

    def configurationFilePath():
        return expanduser("~") + "/" + ".maaConfig"

    def doesConfigurationFilePathExist():
        pass

    def doesConfigurationDictHasAllProperties(configurationDict):
        pass

    def loadCredentialsFromConfigurationFiles():
        pass

def main():
    """ Main program """
    # Code goes over here.
    return 0

if __name__ == "__main__":
    main()